-- MySQL Script generated by MySQL Workbench
-- Fri 22 Aug 2025 02:20:55 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema slrt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema slrt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `slrt` ;
USE `slrt` ;

-- -----------------------------------------------------
-- Table `slrt`.`slrt_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slrt`.`slrt_users` (
  `idusers` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slrt`.`environments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slrt`.`environments` (
  `idenvironments` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idenvironments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slrt`.`pve_environment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slrt`.`pve_environment` (
  `idenvironments` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `hostname` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `port` VARCHAR(45) NULL,
  `datastore_VMs` VARCHAR(45) NULL,
  `vbridge` VARCHAR(45) NULL,
  `datastore_ISO` VARCHAR(45) NULL,
  PRIMARY KEY (`idenvironments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slrt`.`azure-environment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slrt`.`azure-environment` (
  `idenvironments` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idenvironments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slrt`.`pve_vms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slrt`.`pve_vms` (
  `vmid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `IP_address` VARCHAR(45) NULL,
  `Gateway` VARCHAR(45) NULL,
  `VCPUs` INT NULL,
  `DNS-server` VARCHAR(45) NULL,
  `ssh_key` VARCHAR(100) NULL,
  `username` VARCHAR(45) NULL,
  `RAM` INT NULL,
  `Disksize` INT NULL,
  `environmentid` INT NULL,
  PRIMARY KEY (`vmid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slrt`.`environment_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slrt`.`environment_users` (
  `userid` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `environmentid` INT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
